### PR TITLE
Add test cases for CloudLinux 5, 6, and 7

### PR DESCRIPTION
**Pull request by SethMichaelLarson**
I've got test cases here for CloudLinux 5, 6, and 7. CloudLinux 5 and 6 only have `redhat-release` (making them show up with and id of `rhel`) and 7 has `redhat-release` and `os-release` which makes the id show up correctly as `cloudlinux`. None of the three install `lsb-release` by default. So this is another case of inconsistent ids which will have to be solved in a different PR.

This PR solves issue #75.

### CODE REVIEW

**Comment by nir0s** [comment]
First of all, thanks so much. Secondly, there is a normalization function you can use which uses this map:

```python
NORMALIZED_DISTRO_ID = {
    'redhat': 'rhel',  # RHEL 6.x, 7.x
}
```

Just add to it.

Also, there are conflicts after I merged the Mandriva PR. Please rebase, add to the normalization table, and merge.

**Comment by SethMichaelLarson** [comment]
What am I to add to the normalization function? 7 shows up fine but 5 and 6 show up as `redhat` and are normalized to `rhel`.

**Comment by SethMichaelLarson** [comment]
As I understand it distro gets the `id` of a distro-release file from the first word of the file name? So if CloudLinux 5 and 6 only have redhat-release they will always have the id of `rhel` until we have the inconsistencies framework of course.

**Comment by nir0s** [comment]
My bad. That's fine.

**Comment by SethMichaelLarson** [comment]
I don't understand why AppVeyor is not picking up the change, Travis has no problem with it.

**Comment by nir0s** [comment]
It's because it's non-mergable. Please resolve the conflicts first.

**Comment by SethMichaelLarson** [comment]
I resolved the conflicts, GitHub at the very bottom of the checks says "This branch has no conflicts with the base branch".

**Comment by SethMichaelLarson** [comment]
Now AppVeyor takes the commit. Wonder why it didn't like it before. Hm

**Comment by nir0s** [comment]
Um.. I can't merge. There are conflicts. Please rebase on top of master and push.

**Comment by SethMichaelLarson** [comment]
Is GitHub showing us different things? This is what I see from my perspective, it says no conflicts with base branch.

Image

**Comment by nir0s** [comment]
Apologies. I'm rebasing, not merging. If you try to rebase and merge, you'll see that there are conflicts in one of the commits in the tree. Can you please squash, rebase and fix the conflicts? sorry...

**Comment by SethMichaelLarson** [comment]
Oh okay! I can do that! :) I misunderstood what you wanted from me.
I'm making a good start on the `v2` branch, I'll submit it as a PR and we can start collaborating.

**Comment by SethMichaelLarson** [comment]
FYI There's a rebase option in GitHub, if you set it to be the default option I think GitHub will give better hinting about whether a set of commits can be merged. :) Can't confirm this as I haven't used the feature at all but might be worth investigating.

**Comment by SethMichaelLarson** [comment]
This should be ready to go now, can you take a look? :)

**Comment by SethMichaelLarson** [comment]
:tada:

**Pull request merged**
