### PR TITLE
catch and ignore subprocess.CalledProcessError when running `lsb_relsase`

### PR DESCRIPTION
**Pull request by arossert**
A fix for #260 issue.
Ignore `lsb_release` issues.

The other solution that I have is if `lsb_release` installed but the executable is broken, we can just parse `/etc/lsb_release` files to get the same information (maybe it can replace the `subprocess.check_output` completely).

### CODE REVIEW

**Review by yphus — APPROVED** [review]

**Comment by arossert** [comment]
Can this be merged?

**Review by brejoc — APPROVED** [review]
Apart from the linting error I'd say this looks good!

**Comment by brejoc** [comment]
@nir0s Would be really cool if you could take a look at this PR!

**Comment by arossert** [comment]
@nir0s I have fixed the lint issue and the tests to fit the new code, any chance this can be reviewed?

**Comment by brejoc** [comment]
@nir0s Is there a way to get this merged somehow? Is something blocking this PR?

**Comment by arossert** [comment]
@brejoc I’m also waiting for this to be merged. 
It looks like the last activity from @nir0s was on May 29, 2020, let’s hope that this repo is still maintained.

**Comment by brejoc** [comment]
@nir0s Thanks a lot for merging this!

**Comment by arossert** [comment]
@nir0s Thanks a lot, I have been waiting for this one.
Any plans to make a new release soon?

**Comment by arossert** [comment]
@nir0s Can you please make a new release with this fix included?

**Pull request merged**
