### PR TITLE
Update python2.6-support to 1.4.0

### PR DESCRIPTION
**Pull request by abadger**
This updates the python2.6-support branch to the latest code in master (which is what is in the 1.4.0 release).

I chose to merge with master rather than rebase.  Merging results in messier history but rebasing would require anyone collaborating on this branch to remove their branch and re-checkout the branch to continue working on it so I think this is the correct tradeoff.

### CODE REVIEW

**Comment by abadger** [comment]
Appveyor is failing with a strange message: "Fallback clouds stack is too big."  I'll wait and see if the other tests also fail and then see if I can re-kick appveyor.

**Comment by abadger** [comment]
Tests now pass.

**Comment by abadger** [comment]
Doh, I had opened against master instead of against python2.6-support.  Changed the base branch and waiting for tests to pass again.

**Comment by nir0s** [comment]
@abadger sorry for neglecting this. I suggest someone else takes a look if possible, as I'm kinda occupied now and can't validate the PR well. If no one responds in a week or so, I'll take a look.

**Comment by nir0s** [comment]
@abadger, apologies, please resolve the conflicts and I'll merge.

**Comment by abadger** [comment]
Ahh, thanks for taking care of the conflicts :-)

**Comment by nir0s** [comment]
np.. I was out for so long I needed to do something 😉

**Pull request merged**
