### PR TITLE
Some minor code adjustments plus a CLI

### PR DESCRIPTION
**Pull request by nir0s**

### CODE REVIEW

**Comment by nir0s** [comment]
There's a problem with using argparse here. It's not supported by default in 2.6 (which we should still support due to the % of companies using it).

**Comment by asottile** [comment]
For argparse you can do conditional requirements (such as [this example](https://github.com/pre-commit/pre-commit/blob/ea05189c28084e42014b20eae3a1130ea14c9d93/setup.py#L50))

**Comment by andy-maier** [comment]
From looking at the code, it seems that test case `TestCli`assumes that the `distro`command outputs JSON format, but it does that only when invoked with the `-j` option.

**Comment by andy-maier** [comment]
What do people think about an lsb_release compatible cli for distro?

**Comment by nir0s** [comment]
In what sense?

**Comment by nir0s** [comment]
As suggested by @asottile , do we agree that argparse should be conditional and that if someone who uses 2.6 doesn't have argparse it becomes a dependency?

**Comment by MartijnBraam** [comment]
I think that's the better option, I personally find that argparse produces a way better command line tool than optparse.

The oldest python version I used is 2.7 and I don't have any experience with optional dependencies so I don't know the pitfalls but it seems like a good solution.

**Comment by asottile** [comment]
Another option would be to drop 2.6 support (which has been end of lifed for several years).

**Comment by nir0s** [comment]
Many companies still use 2.6. See the PR. I added `argparse` as a conditional requirement.
Also, added an entry point so that you can simply run `distro` instead of `python -m distro`.

**Comment by nir0s** [comment]
If we're going to release 1.0.0, I think we need this in..

**Comment by nir0s** [comment]
solves #133

**Pull request merged**
