### PR TITLE
Use TOXENV environment variable

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by andy-maier** [comment]
+1

**Comment by nir0s** [comment]
Please fix conflicts

**Comment by asottile** [comment]
Rebased to fix conflicts :)

**Comment by nir0s** [comment]
This is somewhat less explicit. For instance. travis shows:

```
pip 8.1.2 from /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (python 3.5)
```

Not saying that we shouldn't merge.. but It's somewhat harder to see the environment like that during tests.

**Comment by asottile** [comment]
Previously you were setting python for the tox executable's sake only. I've
removed that bit since it's unnecessary.  The messaging you are seeing
comes from travis-ci directly.  I don't know of a way to turn it off

**Pull request merged**
